### ISSUE TITLE
io.api.etherscan.error.ConnectionException: Server error: Bad Gateway

### ISSUE THREAD

**Issue by deniben** [GoodforGod/java-etherscan-api#10]
```
Exception in thread "main" io.api.etherscan.error.ConnectionException: Server error: Bad Gateway
	at io.api.etherscan.executor.impl.HttpExecutor.get(HttpExecutor.java:102)
	at io.api.etherscan.core.impl.BasicProvider.getRequest(BasicProvider.java:73)
	at io.api.etherscan.core.impl.BasicProvider.getRequest(BasicProvider.java:87)
	at io.api.etherscan.core.impl.AccountApiProvider.balance(AccountApiProvider.java:63)
	at info.www.Main3.main(Main3.java:40)
Caused by: io.api.etherscan.error.ConnectionException: Server error: Bad Gateway
	at io.api.etherscan.executor.impl.HttpExecutor.get(HttpExecutor.java:93)
Caused by: io.api.etherscan.error.ConnectionException: Server error: Bad Gateway
```
```
Main 40
  for(int i = 0; i < 10000; i++){
...
                Balance balance = api.account().balance(address);
...
}
```

**Comment by GoodforGod** [comment]
All tests are actually passing for this logic:
https://github.com/GoodforGod/java-etherscan-api/blob/master/src/test/java/io/api/etherscan/EtherScanApiTest.java#L54

So that's probably some temporary issue on server or something on your side.
